% AUTOGENERATED 29-Feb-2020 by C:\Users\user\Documents\RobotController\repositories\RoboTools\@SerialManipulator\generateJacobian
% Computes the jaociban for variables Q and frame i
% Q -> 6 x 1 vector of joint variables
% i -> the frame number. 
%       1 - n : frame
function J = codegen_jacobianSingle(Q, i)
    %#codegen
    i = int8(i);
          
    % Get frame
    switch i
        
		case 1
			J = codegen_jacobian_1(Q);

		case 2
			J = codegen_jacobian_2(Q);

		case 3
			J = codegen_jacobian_3(Q);

		case 4
			J = codegen_jacobian_4(Q);

		case 5
			J = codegen_jacobian_5(Q);

		case 6
			J = codegen_jacobian_6(Q);

        
        otherwise
            error('No such frame defined');
    end
        
end