% AUTOGENERATED 29-Feb-2020 by C:\Users\user\Documents\RobotController\repositories\RoboTools\@SerialManipulator\generateMakeIDFunction

function id = codegen_FK_getMakeID
    %#codegen
    
    id = '4d5f65b742253a397afec638949e24fe';
        
end