% AUTOGENERATED 11-Feb-2020 by /Users/steffanlloyd/Documents/School/00_Thesis/Robodeb/repositories/RoboTools/@SerialManipulator/generateHelperFunctions

function id = codegen_getMakeID
    %#codegen
    
    id = 'b7b90e26bbd652c3a79128d552ed6141';
        
end