function G = codegen_EE_gravityVector(in1,in2)
%CODEGEN_EE_GRAVITYVECTOR
%    G = CODEGEN_EE_GRAVITYVECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Feb-2020 09:42:05

%Inputs: Q, Xtool.
m_tool = in2(:,1);
q_2 = in1(2,:);
q_3 = in1(3,:);
q_4 = in1(4,:);
r_c_tool_x = in2(:,2);
r_c_tool_y = in2(:,3);
r_c_tool_z = in2(:,4);
t2 = cos(q_4);
t3 = sin(q_4);
t4 = q_2+q_3;
t5 = cos(t4);
t6 = sin(t4);
t7 = t6.*-2.95e-1;
t8 = t6.*2.95e-1;
t9 = t5.*9.0e-2;
t10 = r_c_tool_y.*t6;
t11 = r_c_tool_z.*t3.*t5;
t12 = r_c_tool_x.*t2.*t5.*-1.0;
t13 = r_c_tool_x.*t2.*t5.*1.0;
G = [0.0;m_tool.*(t7+t9+t10+t11+t12-sin(q_2).*2.7e-1).*9.806132;m_tool.*(t7+t9+t10+t11+t12).*9.806132;m_tool.*t6.*(r_c_tool_x.*t3+r_c_tool_z.*t2).*9.806132];
