function Jt = codegen_jacobian_tool(in1,in2)
%CODEGEN_JACOBIAN_TOOL
%    JT = CODEGEN_JACOBIAN_TOOL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Feb-2020 15:36:10

%Input order: Q, dtool
d_tool_x = in2(1,:);
d_tool_y = in2(2,:);
d_tool_z = in2(3,:);
q_1 = in1(1,:);
q_2 = in1(2,:);
q_3 = in1(3,:);
q_4 = in1(4,:);
t2 = cos(q_1);
t3 = cos(q_2);
t4 = cos(q_3);
t5 = cos(q_4);
t6 = sin(q_1);
t7 = sin(q_2);
t8 = sin(q_3);
t9 = sin(q_4);
t10 = q_2+q_3;
t17 = -q_4;
t11 = t3.*2.7e-1;
t12 = t6.*-1.0;
t13 = t6.*1.0;
t14 = cos(t10);
t15 = q_4+t10;
t16 = sin(t10);
t28 = t10+t17;
t18 = cos(t15);
t19 = sin(t15);
t20 = t14.*-2.95e-1;
t21 = t14.*2.95e-1;
t22 = t16.*-2.95e-1;
t23 = t16.*2.95e-1;
t24 = t14.*9.0e-2;
t25 = t16.*-9.0e-2;
t26 = t16.*9.0e-2;
t27 = d_tool_y.*t16;
t29 = d_tool_y.*t14.*-1.0;
t30 = d_tool_y.*t14.*1.0;
t37 = cos(t28);
t38 = sin(t28);
t31 = d_tool_x.*t18.*-5.0e-1;
t32 = d_tool_x.*t18.*5.0e-1;
t33 = d_tool_z.*t18.*5.0e-1;
t34 = d_tool_x.*t19.*-5.0e-1;
t35 = d_tool_x.*t19.*5.0e-1;
t36 = d_tool_z.*t19.*5.0e-1;
t39 = (d_tool_z.*t18)./2.0;
t40 = (d_tool_x.*t19)./2.0;
t41 = d_tool_x.*t37.*-5.0e-1;
t42 = d_tool_x.*t37.*5.0e-1;
t43 = d_tool_z.*t37.*-5.0e-1;
t44 = d_tool_z.*t37.*5.0e-1;
t45 = d_tool_x.*t38.*-5.0e-1;
t46 = d_tool_x.*t38.*5.0e-1;
t47 = d_tool_z.*t38.*-5.0e-1;
t48 = d_tool_z.*t38.*5.0e-1;
t50 = (d_tool_z.*t37)./2.0;
t51 = (d_tool_x.*t38)./2.0;
t49 = -t39;
t52 = t20+t25+t30+t33+t40+t43+t51;
t53 = t11+t21+t26+t29+t34+t45+t49+t50;
Jt = reshape([t6.*-7.5e-2-t6.*t7.*2.7e-1-d_tool_z.*t2.*t5.*1.0-d_tool_x.*t2.*t9.*1.0+t3.*t4.*t6.*9.0e-2-t3.*t6.*t8.*2.95e-1-t4.*t6.*t7.*2.95e-1-t6.*t7.*t8.*9.0e-2+d_tool_y.*t3.*t6.*t8+d_tool_y.*t4.*t6.*t7+d_tool_x.*t3.*t4.*t5.*t12+d_tool_z.*t3.*t4.*t6.*t9+d_tool_x.*t5.*t6.*t7.*t8+d_tool_z.*t7.*t8.*t9.*t12,t2.*7.5e-2+t2.*t7.*2.7e-1+d_tool_z.*t5.*t12+d_tool_x.*t9.*t12-t2.*t3.*t4.*9.0e-2+t2.*t3.*t8.*2.95e-1+t2.*t4.*t7.*2.95e-1+t2.*t7.*t8.*9.0e-2-d_tool_y.*t2.*t3.*t8.*1.0-d_tool_y.*t2.*t4.*t7.*1.0+d_tool_x.*t2.*t3.*t4.*t5-d_tool_z.*t2.*t3.*t4.*t9.*1.0-d_tool_x.*t2.*t5.*t7.*t8.*1.0+d_tool_z.*t2.*t7.*t8.*t9,0.0,0.0,0.0,1.0,t2.*t53,t6.*t53,t7.*-2.7e-1+t22+t24+t27+t31+t36+t41+t47,t12,t2,0.0,t2.*t52.*-1.0,t12.*t52,t22+t24+t27+t31+t36+t41+t47,t12,t2,0.0,-d_tool_x.*t5.*t6+d_tool_z.*t6.*t9-d_tool_z.*t2.*t3.*t4.*t5-d_tool_x.*t2.*t3.*t4.*t9+d_tool_z.*t2.*t5.*t7.*t8+d_tool_x.*t2.*t7.*t8.*t9,d_tool_x.*t2.*t5-d_tool_z.*t2.*t9.*1.0+d_tool_z.*t3.*t4.*t5.*t12+d_tool_x.*t3.*t4.*t9.*t12+d_tool_z.*t5.*t6.*t7.*t8+d_tool_x.*t6.*t7.*t8.*t9,t16.*(d_tool_z.*t5+d_tool_x.*t9),t2.*t16,t6.*t16,t14],[6,4]);
