function G = codegen_gravityVector(in1)
%CODEGEN_GRAVITYVECTOR
%    G = CODEGEN_GRAVITYVECTOR(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Feb-2020 09:42:05

%Inputs: Q.
q_2 = in1(2,:);
q_3 = in1(3,:);
q_4 = in1(4,:);
t2 = cos(q_4);
t3 = sin(q_4);
t4 = q_2+q_3;
t5 = cos(t4);
t6 = sin(t4);
G = [0.0;t5.*5.648332032-t6.*5.76021999812-cos(q_2-1.564997896182638).*2.935887601987031e+1+t2.*t5.*2.84377828e-2-t3.*t5.*7.962579184e-2;t5.*5.648332032-t6.*5.76021999812+t2.*t5.*2.84377828e-2-t3.*t5.*7.962579184e-2;t6.*cos(q_4-3.430239404207034e-1).*-8.455160682522235e-2];
