function T = codegen_FK_2(in1)
%CODEGEN_FK_2
%    T = CODEGEN_FK_2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Feb-2020 15:36:02

%Input order: Q.
q_1 = in1(1,:);
q_2 = in1(2,:);
t2 = cos(q_1);
t3 = cos(q_2);
t4 = sin(q_1);
t5 = sin(q_2);
t6 = t5.*2.7e-1;
t7 = t6+7.5e-2;
T = reshape([t2.*t5.*-1.0,t4.*t5.*-1.0,t3.*-1.0,0.0,t2.*t3.*-1.0,t3.*t4.*-1.0,t5,0.0,t4.*-1.0,t2,0.0,0.0,t2.*t7,t4.*t7,t3.*2.7e-1+1.32e-1,1.0],[4,4]);
