function Jp = codegen_jacobianPoint_3(in1,in2)
%CODEGEN_JACOBIANPOINT_3
%    JP = CODEGEN_JACOBIANPOINT_3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Feb-2020 15:36:14

%Input order: Q, r
q_1 = in1(1,:);
q_2 = in1(2,:);
q_3 = in1(3,:);
r_1 = in2(1,:);
r_2 = in2(2,:);
r_3 = in2(3,:);
t2 = cos(q_1);
t3 = cos(q_2);
t4 = sin(q_1);
t5 = sin(q_2);
t6 = q_2+q_3;
t7 = t3.*2.7e-1;
t8 = t4.*-1.0;
t9 = t4.*1.0;
t10 = cos(t6);
t11 = sin(t6);
t12 = t10.*9.0e-2;
t13 = t11.*9.0e-2;
t14 = r_3.*t10;
t15 = r_1.*t10.*-1.0;
t16 = r_1.*t10.*1.0;
t17 = r_1.*t11.*-1.0;
t18 = r_1.*t11.*1.0;
t19 = r_3.*t11.*-1.0;
t20 = r_3.*t11.*1.0;
t21 = t13+t14+t17;
t22 = t7+t21;
Jp = reshape([t4.*-7.5e-2-r_2.*t2.*1.0-t4.*t5.*2.7e-1+t4.*t12+r_1.*t8.*t10+r_3.*t8.*t11,t2.*7.5e-2+r_2.*t8+t2.*t5.*2.7e-1-t2.*t10.*9.0e-2+r_1.*t2.*t10+r_3.*t2.*t11,0.0,0.0,0.0,1.0,t2.*t22,t4.*t22,t5.*-2.7e-1+t12+t15+t19,t8,t2,0.0,t2.*t21,t4.*t21,t12+t15+t19,t8,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,4]);
