% AUTOGENERATED 11-Feb-2020 by /Users/steffanlloyd/Documents/School/00_Thesis/Robodeb/repositories/RoboTools/@SerialManipulator/generateJacobian
% Computes the jacobbian for variables Q and frame i
% Q -> 6 x 1 vector of joint variables
% i -> the frame number. 
%       1 - n : frame
function Jp = codegen_jacobianPointSingle(Q, i, r)
    %#codegen
    i = int8(i);
          
    % Get frame
    switch i
        
		case 1
			Jp = codegen_jacobianPoint_1(Q, r);

		case 2
			Jp = codegen_jacobianPoint_2(Q, r);

		case 3
			Jp = codegen_jacobianPoint_3(Q, r);

		case 4
			Jp = codegen_jacobianPoint_4(Q, r);

        
        otherwise
            error('No such frame defined');
    end
        
end