function G = codegen_gravityVector(in1)
%CODEGEN_GRAVITYVECTOR
%    G = CODEGEN_GRAVITYVECTOR(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Feb-2020 13:35:20

%Inputs: Q.
q_2 = in1(2,:);
q_3 = in1(3,:);
q_4 = in1(4,:);
q_5 = in1(5,:);
G = [0.0;cos(q_2+q_3).*6.4779307992-sin(q_2+q_3).*8.47946040172-cos(q_2).*1.7023445152e-1-sin(q_2).*3.184717877376e+1+cos(q_2+q_3).*cos(q_4).*2.84377828e-2-cos(q_2+q_3).*sin(q_4).*3.5615871424e-1-cos(q_2).*cos(q_5).*sin(q_3).*9.7708299248e-2-cos(q_3).*cos(q_5).*sin(q_2).*9.7708299248e-2+cos(q_2).*sin(q_3).*sin(q_5).*9.21776408e-4+cos(q_3).*sin(q_2).*sin(q_5).*9.21776408e-4-cos(q_2).*cos(q_3).*cos(q_4).*cos(q_5).*9.21776408e-4-cos(q_2).*cos(q_3).*cos(q_4).*sin(q_5).*9.7708299248e-2+cos(q_4).*cos(q_5).*sin(q_2).*sin(q_3).*9.21776408e-4+cos(q_4).*sin(q_2).*sin(q_3).*sin(q_5).*9.7708299248e-2;cos(q_2+q_3).*6.4779307992-sin(q_2+q_3).*8.47946040172+cos(q_2+q_3).*cos(q_4).*2.84377828e-2-cos(q_2+q_3).*sin(q_4).*3.5615871424e-1-cos(q_2).*cos(q_5).*sin(q_3).*9.7708299248e-2-cos(q_3).*cos(q_5).*sin(q_2).*9.7708299248e-2+cos(q_2).*sin(q_3).*sin(q_5).*9.21776408e-4+cos(q_3).*sin(q_2).*sin(q_5).*9.21776408e-4-cos(q_2).*cos(q_3).*cos(q_4).*cos(q_5).*9.21776408e-4-cos(q_2).*cos(q_3).*cos(q_4).*sin(q_5).*9.7708299248e-2+cos(q_4).*cos(q_5).*sin(q_2).*sin(q_3).*9.21776408e-4+cos(q_4).*sin(q_2).*sin(q_3).*sin(q_5).*9.7708299248e-2;sin(q_2+q_3).*cos(q_4).*-3.5615871424e-1-sin(q_2+q_3).*sin(q_4).*2.84377828e-2+cos(q_2).*cos(q_5).*sin(q_3).*sin(q_4).*9.21776408e-4+cos(q_3).*cos(q_5).*sin(q_2).*sin(q_4).*9.21776408e-4+cos(q_2).*sin(q_3).*sin(q_4).*sin(q_5).*9.7708299248e-2+cos(q_3).*sin(q_2).*sin(q_4).*sin(q_5).*9.7708299248e-2;sin(q_2).*sin(q_3).*sin(q_5).*9.7708299248e-2-cos(q_2).*cos(q_3).*cos(q_5).*9.21776408e-4-cos(q_2).*cos(q_3).*sin(q_5).*9.7708299248e-2+cos(q_5).*sin(q_2).*sin(q_3).*9.21776408e-4-cos(q_2).*cos(q_4).*cos(q_5).*sin(q_3).*9.7708299248e-2-cos(q_3).*cos(q_4).*cos(q_5).*sin(q_2).*9.7708299248e-2+cos(q_2).*cos(q_4).*sin(q_3).*sin(q_5).*9.21776408e-4+cos(q_3).*cos(q_4).*sin(q_2).*sin(q_5).*9.21776408e-4];
