% AUTOGENERATED 11-Feb-2020 by /Users/steffanlloyd/Documents/School/00_Thesis/Robodeb/repositories/RoboTools/@SerialManipulator/generateHelperFunctions

function id = codegen_getMakeID
    %#codegen
    
    id = '0dcffaa021ec38143ed73e0db8e52f82';
        
end