function T = codegen_FK_3(in1)
%CODEGEN_FK_3
%    T = CODEGEN_FK_3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Feb-2020 00:21:05

%Input order: Q.
q_1 = in1(1,:);
q_2 = in1(2,:);
q_3 = in1(3,:);
t2 = cos(q_1);
t3 = sin(q_1);
t4 = sin(q_2);
t5 = q_2+q_3;
t6 = t4.*2.7e-1;
t7 = cos(t5);
t8 = sin(t5);
t9 = t7.*-9.0e-2;
t10 = t7.*9.0e-2;
t11 = t6+t9+7.5e-2;
T = reshape([t2.*t7,t3.*t7,t8.*-1.0,0.0,t3.*-1.0,t2,0.0,0.0,t2.*t8,t3.*t8,t7,0.0,t2.*t11,t3.*t11,t8.*9.0e-2+cos(q_2).*2.7e-1+1.32e-1,1.0],[4,4]);
