function J = codegen_jacobian_4(in1)
%CODEGEN_JACOBIAN_4
%    J = CODEGEN_JACOBIAN_4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Feb-2020 00:21:33

%Input order: Q
q_1 = in1(1,:);
q_2 = in1(2,:);
q_3 = in1(3,:);
t2 = cos(q_1);
t3 = cos(q_2);
t4 = sin(q_1);
t5 = sin(q_2);
t6 = q_2+q_3;
t7 = t3.*2.7e-1;
t8 = t4.*-1.0;
t9 = t4.*1.0;
t10 = t5.*2.7e-1;
t11 = t6-2.961151458749647e-1;
t12 = t6+1.274681180919932;
t13 = sin(t6);
t14 = cos(t11);
t15 = cos(t12);
t16 = t14.*3.084234102658227e-1;
t17 = t15.*-3.084234102658227e-1;
t18 = t15.*3.084234102658227e-1;
t19 = t7+t16;
t20 = t10+t17+7.5e-2;
J = reshape([t8.*t20,t2.*t20,0.0,0.0,0.0,1.0,t2.*t19,t4.*t19,-t10+t18,t8,t2,0.0,t2.*t14.*3.084234102658227e-1,t4.*t14.*3.084234102658227e-1,t15.*3.084234102658227e-1,t8,t2,0.0,0.0,0.0,0.0,t2.*t13,t4.*t13,cos(t6),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
