function Jp = codegen_jacobianPoint_1(in1,in2)
%CODEGEN_JACOBIANPOINT_1
%    JP = CODEGEN_JACOBIANPOINT_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Feb-2020 00:22:00

%Input order: Q, r
q_1 = in1(1,:);
r_1 = in2(1,:);
r_3 = in2(3,:);
t2 = cos(q_1);
t3 = conj(r_1);
t4 = conj(r_3);
t5 = sin(q_1);
Jp = reshape([t5.*-7.5e-2-t2.*t4.*1.0-t3.*t5.*1.0,t2.*7.5e-2+t2.*t3-t4.*t5.*1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
