function T = codegen_dynamicsTheta(in1,in2,in3)
%CODEGEN_DYNAMICSTHETA
%    T = CODEGEN_DYNAMICSTHETA(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Mar-2020 00:39:44

% Regressor generated to work with the following theta matrix:
% 
%  T =
% 
% 	I_xx_5 - 1.0*I_yy_5 - 1.0*I_zz_5 - 2.0*m_5*r_cx_5^2
% 	I_xx_2 + I_xx_3 + I_xx_4 + I_yy_1 + I_zz_5 + 0.005625*m_1 + 0.15*m_1*r_cx_1 + 0.020833333333333333333333333333333*m_2*r_cx_2 - 0.295*m_3*r_cz_3 - 0.295*m_4*r_cy_4 + m_1*r_cx_1^2 + m_1*r_cz_1^2 + m_2*r_cy_2^2 + m_2*r_cz_2^2 + m_3*r_cy_3^2 + m_3*r_cz_3^2 + m_4*r_cy_4^2 + m_4*r_cz_4^2 + m_5*r_cx_5^2 + m_5*r_cy_5^2
% 	I_xx_2 - 1.0*I_yy_2 + I_zz_2 + 2.0*m_2*r_cy_2^2
% 	I_xx_4 + I_yy_4 - 1.0*I_zz_4 + 2.0*I_zz_5 + 2.0*m_4*r_cz_4^2 + 2.0*m_5*r_cx_5^2 + 2.0*m_5*r_cy_5^2
% 	I_xx_6 - 1.0*I_yy_6 + I_zz_6 + 2.0*m_6*r_cy_6^2
% 	I_xx_3 + 2.0*I_xx_4 + I_yy_3 - 1.0*I_zz_3 + 2.0*I_zz_5 - 0.59*m_3*r_cz_3 - 0.59*m_4*r_cy_4 + 2.0*m_3*r_cz_3^2 + 2.0*m_4*r_cy_4^2 + 2.0*m_4*r_cz_4^2 + 2.0*m_5*r_cx_5^2 + 2.0*m_5*r_cy_5^2
% 	m_2 - 3.7037037037037037037037037037037*m_2*r_cx_2 + 11.111111111111111111111111111111*m_3*r_cx_3
% 	m_3 - 11.111111111111111111111111111111*m_3*r_cx_3 - 3.3898305084745762711864406779661*m_3*r_cz_3 + 3.3898305084745762711864406779661*m_4*r_cy_4
% 	m_4 + m_5 + 3.3898305084745762711864406779661*m_3*r_cz_3 - 3.3898305084745762711864406779661*m_4*r_cy_4 - 12.5*m_5*r_cz_5 - 12.5*m_6*r_cz_6
% 	m_6 + 12.5*m_5*r_cz_5 + 12.5*m_6*r_cz_6
% 	I_zz_2 - 0.27*m_2*r_cx_2 + m_2*r_cx_2^2 + m_2*r_cy_2^2
% 	I_xx_4 + I_yy_3 + I_zz_5 - 0.09*m_3*r_cx_3 - 0.295*m_3*r_cz_3 - 0.295*m_4*r_cy_4 + m_3*r_cx_3^2 + m_3*r_cz_3^2 + m_4*r_cy_4^2 + m_4*r_cz_4^2 + m_5*r_cx_5^2 + m_5*r_cy_5^2
% 	I_xx_4 - 1.0*I_zz_4 + I_zz_5 - 1.0*m_4*r_cx_4^2 + m_4*r_cz_4^2 + m_5*r_cx_5^2 + m_5*r_cy_5^2
% 	I_xx_6 + I_yy_5 - 0.08*m_5*r_cz_5 + 0.08*m_6*r_cz_6 + m_5*r_cx_5^2 + m_5*r_cz_5^2 + m_6*r_cy_6^2 + m_6*r_cz_6^2
% 	I_zz_6 + m_6*r_cx_6^2 + m_6*r_cy_6^2
% 	I_yz_2 - 1.0*m_2*r_cy_2*r_cz_2
% 	I_xz_2 + 0.27*m_2*r_cz_2 + 0.27*m_3*r_cy_3 - 1.0*m_2*r_cx_2*r_cz_2
% 	I_xy_2 - 1.0*m_2*r_cx_2*r_cy_2
% 	I_xz_3 - 1.0*m_3*r_cx_3*r_cz_3
% 	I_xz_5 - 1.0*m_5*r_cx_5*r_cz_5
% 	I_xy_6 - 1.0*m_6*r_cx_6*r_cy_6
% 	m_2*r_cy_2
% 	I_xy_3 + 0.09*m_3*r_cy_3 - 1.0*m_3*r_cx_3*r_cy_3
% 	I_xz_4 - 1.0*m_4*r_cx_4*r_cz_4
% 	I_yz_3 - 1.0*m_3*r_cy_3*r_cz_3
% 	I_xy_4 - 1.0*m_4*r_cx_4*r_cy_4
% 	I_xz_6 - 1.0*m_6*r_cx_6*r_cz_6
% 	I_yz_4 - 1.0*m_4*r_cy_4*r_cz_4
% 	I_yz_6 - 1.0*m_6*r_cy_6*r_cz_6
% 	m_4*r_cx_4
% 	m_4*r_cz_4 + m_5*r_cy_5
% 	m_5*r_cx_5
% 	m_6*r_cy_6
% 	I_yz_5 - 1.0*m_5*r_cy_5*r_cz_5
% 	I_xy_5 - 1.0*m_5*r_cx_5*r_cy_5
% 	m_6*r_cx_6
% 
% Robot make ID: 138b1743f7920878dae4d9710d2c69a5
I_xx_2 = in1(2);
I_xx_3 = in1(3);
I_xy_2 = in1(20);
I_xx_4 = in1(4);
I_xy_3 = in1(21);
I_xz_2 = in1(26);
I_xx_5 = in1(5);
I_xy_4 = in1(22);
I_xz_3 = in1(27);
I_xx_6 = in1(6);
I_xy_5 = in1(23);
I_xz_4 = in1(28);
I_xy_6 = in1(24);
I_xz_5 = in1(29);
I_xz_6 = in1(30);
I_yy_1 = in1(7);
I_yy_2 = in1(8);
I_yy_3 = in1(9);
I_yz_2 = in1(32);
I_yy_4 = in1(10);
I_yz_3 = in1(33);
I_yy_5 = in1(11);
I_yz_4 = in1(34);
I_yy_6 = in1(12);
I_yz_5 = in1(35);
I_yz_6 = in1(36);
I_zz_2 = in1(14);
I_zz_3 = in1(15);
I_zz_4 = in1(16);
I_zz_5 = in1(17);
I_zz_6 = in1(18);
m_1 = in2(1,:);
m_2 = in2(2,:);
m_3 = in2(3,:);
m_4 = in2(4,:);
m_5 = in2(5,:);
m_6 = in2(6,:);
r_cx_1 = in3(1);
r_cx_2 = in3(4);
r_cx_3 = in3(7);
r_cy_2 = in3(5);
r_cz_1 = in3(3);
r_cx_4 = in3(10);
r_cy_3 = in3(8);
r_cz_2 = in3(6);
r_cx_5 = in3(13);
r_cy_4 = in3(11);
r_cz_3 = in3(9);
r_cx_6 = in3(16);
r_cy_5 = in3(14);
r_cz_4 = in3(12);
r_cy_6 = in3(17);
r_cz_5 = in3(15);
r_cz_6 = in3(18);
t2 = r_cy_2.^2;
t3 = r_cx_5.^2;
t4 = r_cy_4.^2;
t5 = r_cz_3.^2;
t6 = r_cy_5.^2;
t7 = r_cz_4.^2;
t8 = r_cy_6.^2;
t9 = I_zz_4.*-1.0;
t10 = I_zz_4.*1.0;
t11 = I_zz_5.*2.0;
t12 = m_3.*r_cz_3.*-2.95e-1;
t13 = m_3.*r_cz_3.*2.95e-1;
t14 = m_4.*r_cy_4.*-2.95e-1;
t15 = m_4.*r_cy_4.*2.95e-1;
t16 = m_3.*r_cx_3.*1.111111111111111e+1;
t17 = m_5.*r_cz_5.*1.25e+1;
t18 = m_6.*r_cz_6.*1.25e+1;
t19 = m_3.*r_cz_3.*3.389830508474576;
t20 = m_4.*r_cy_4.*3.389830508474576;
t21 = m_2.*t2;
t22 = m_3.*t5;
t23 = m_4.*t4;
t24 = m_4.*t7;
t25 = m_5.*t3;
t26 = m_5.*t6;
t27 = m_6.*t8;
t28 = t24.*2.0;
t29 = t25.*2.0;
t30 = t26.*2.0;
T = [I_xx_5-I_yy_5.*1.0-I_zz_5.*1.0-t29;I_xx_2+I_xx_3+I_xx_4+I_yy_1+I_zz_5+m_1.*5.625e-3+t12+t14+t21+t22+t23+t24+t25+t26+m_1.*r_cx_1.*1.5e-1+m_2.*r_cx_2.*2.083333333333333e-2+m_1.*r_cx_1.^2+m_1.*r_cz_1.^2+m_2.*r_cz_2.^2+m_3.*r_cy_3.^2;I_xx_2-I_yy_2.*1.0+I_zz_2+t21.*2.0;I_xx_4+I_yy_4+t9+t11+t28+t29+t30;I_xx_6-I_yy_6.*1.0+I_zz_6+t27.*2.0;I_xx_3+I_xx_4.*2.0+I_yy_3-I_zz_3.*1.0+t11+t22.*2.0+t23.*2.0+t28+t29+t30-m_3.*r_cz_3.*5.9e-1-m_4.*r_cy_4.*5.9e-1;m_2+t16-m_2.*r_cx_2.*3.703703703703704;m_3-t16-t19+t20;m_4+m_5-t17-t18+t19-t20;m_6+t17+t18;I_zz_2+t21-m_2.*r_cx_2.*2.7e-1+m_2.*r_cx_2.^2;I_xx_4+I_yy_3+I_zz_5+t12+t14+t22+t23+t24+t25+t26-m_3.*r_cx_3.*9.0e-2+m_3.*r_cx_3.^2;I_xx_4+I_zz_5+t9+t24+t25+t26-m_4.*r_cx_4.^2.*1.0;I_xx_6+I_yy_5+t25+t27-m_5.*r_cz_5.*8.0e-2+m_6.*r_cz_6.*8.0e-2+m_5.*r_cz_5.^2+m_6.*r_cz_6.^2;I_zz_6+t27+m_6.*r_cx_6.^2;I_yz_2-m_2.*r_cy_2.*r_cz_2.*1.0;I_xz_2+m_2.*r_cz_2.*2.7e-1+m_3.*r_cy_3.*2.7e-1-m_2.*r_cx_2.*r_cz_2.*1.0;I_xy_2-m_2.*r_cx_2.*r_cy_2.*1.0;I_xz_3-m_3.*r_cx_3.*r_cz_3.*1.0;I_xz_5-m_5.*r_cx_5.*r_cz_5.*1.0;I_xy_6-m_6.*r_cx_6.*r_cy_6.*1.0;m_2.*r_cy_2;I_xy_3+m_3.*r_cy_3.*9.0e-2-m_3.*r_cx_3.*r_cy_3.*1.0;I_xz_4-m_4.*r_cx_4.*r_cz_4.*1.0;I_yz_3-m_3.*r_cy_3.*r_cz_3.*1.0;I_xy_4-m_4.*r_cx_4.*r_cy_4.*1.0;I_xz_6-m_6.*r_cx_6.*r_cz_6.*1.0;I_yz_4-m_4.*r_cy_4.*r_cz_4.*1.0;I_yz_6-m_6.*r_cy_6.*r_cz_6.*1.0;m_4.*r_cx_4;m_4.*r_cz_4+m_5.*r_cy_5;m_5.*r_cx_5;m_6.*r_cy_6;I_yz_5-m_5.*r_cy_5.*r_cz_5.*1.0;I_xy_5-m_5.*r_cx_5.*r_cy_5.*1.0;m_6.*r_cx_6];
