% AUTOGENERATED 01-Mar-2020 by C:\Users\user\Documents\RobotController\repositories\RoboTools\@SerialManipulator\generateMakeIDFunction

function id = codegen_reg_dynamics_getMakeID
    %#codegen
    
    id = '138b1743f7920878dae4d9710d2c69a5';
        
end